# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    target-branch: "master"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    target-branch: "master"
  - package-ecosystem: "npm"
    directory: "/searx/static/themes/oscar"
    schedule:
      interval: "weekly"
      day: "friday"
    target-branch: "master"
  - package-ecosystem: "npm"
    directory: "/searx/static/themes/simple"
    schedule:
      interval: "weekly"
      day: "friday"
    target-branch: "master"
