name: Compile themes

on:
  pull_request:
    paths:
      - 'searx/static/themes/**'

jobs:
  compile:
    name: Compiled and update themes
    runs-on: ubuntu-20.04
    env:
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Ubuntu packages
        run: sudo ./utils/searx.sh install packages
      - name: Install node dependencies
        run: make V=1 node.env
      - name: Build themes
        run: make V=1 themes.all
      - name: Add, commit and push
        uses: EndBug/add-and-commit@v7
        with:
          add: 'searx/static/themes/'
          author_name: searxng-bot
          author_email: searxng-bot@users.noreply.github.com
          message: '[bot] PR #${{ github.event.number }}: Automatic themes compilation'
